allowBuilds:
  core-js: set this to true or false
  core-js-pure: set this to true or false
  es5-ext: set this to true or false
  fsevents: set this to true or false
  node-pty: set this to true or false
  sharp: set this to true or false
